# Generated by Django 5.0.2 on 2024-03-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_post_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.RemoveField(
            model_name='club',
            name='type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='admin_id',
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='club',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
