# Generated by Django 5.0.2 on 2024-03-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_club_admin_id_remove_club_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('role_status', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
