# Generated by Django 5.0.2 on 2024-03-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=75)),
                ('status', models.CharField(max_length=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.type')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('post_description', models.CharField(max_length=255)),
                ('post_deletion_date', models.CharField(blank=True, max_length=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.user')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.club')),
            ],
        ),
    ]
